### ISSUE TITLE
Unable to update account with email or username flag

### ISSUE THREAD

**Issue by jgwerner** [3Blades/cli-tools#80]
When attempting to update an account by using the `--email` flag or `--username` flag as the account identifier, tbs returns:

    Error: unknown error (status 405): {resp:0xc420520090}

For example, both `tbs account update --username greg` and `tbs account update --email werner.greg@gmail.com` return the same error.

When using `tbs account update --uuid id_goes_here` then a proper response is obtained.

**Comment by johngriebel** [comment]
@jgwerner - It seems this is because the `--email` and `--username` flags imply that you are updating those fields. We should definitely allow users to update their email, but I believe we decided against allowing them to change their username. Furthermore, I think we should remove the `--uuid` flag since the API doesn't require the `id` anymore, and simply assumes you're operating on the authenticated user. Thoughts?

**Comment by jgwerner** [comment]
@jkp85 @johngriebel if we can't update account username with `tbs account update --username xyz` then we should disable that flag. I believe the `--uuid` flag should not be there, since as you stated the user account's uuid should be associated to the account authenticated with CLI Tools `tbs login` --> `eval $(tbs env --namespace xyz)` commands.
